FROM python:3.10-slim

# Add code location code
WORKDIR /opt/dagster/app

COPY pdga/analytics/requirements.txt .
RUN pip install -r requirements.txt

COPY pdga /opt/dagster/app
RUN dagster-dbt project prepare-and-package --file /opt/dagster/app/project.py
RUN apt upgrade
#RUN apt install postgresql-client

# Run dagster code server on port 4000
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]