pdga_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
      user: '{{ env_var("SNOWFLAKE_USER") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      
      warehouse: 'PDGA_WH'
      database: 'PDGA_DB'
      schema: 'PDGA'
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt
